name: "Publish template"

on:
  push:
    tags:
      - "v*"

jobs:
  publish-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Prebuild java-nodejs dev container
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
